version: "3"

networks:
  ethernet:
    external: true

services:
  gl-static-api-php:
    container_name: gl-static-api-php
    build: .docker/php/${APP_ENV:-dev}
    volumes:
      - .:/app
    command: sh /srv/scripts/post-run.sh
    networks:
      - ethernet
  gl-static-api-nginx:
    container_name: gl-static-api-nginx
    build: .docker/nginx
    volumes:
      - .:/app
    ports:
      - "8003:80"
    networks:
      - ethernet
  gl-static-api-varnish:
    container_name: gl-static-api-varnish
    build: .docker/varnish
    ports:
      - "8004:80"
    depends_on:
      - gl-static-api-nginx
    links:
      - gl-static-api-nginx
    networks:
      - ethernet


