version: "2.1"

services:
  gl-static-api-php:
    container_name: gl-static-api-php
    build: .docker/php/${APP_ENV:-dev}
    volumes:
      - .:/app
    command: sh /srv/scripts/post-run.sh
  gl-static-api-nginx:
    container_name: gl-static-api-nginx
    build: .docker/nginx
    volumes_from:
      - gl-static-api-php
    ports:
      - "8003:80"
  gl-static-api-varnish:
    container_name: gl-static-api-varnish
    build: .docker/varnish
    ports:
      - "8004:80"
    depends_on:
      - gl-static-api-nginx
    links:
      - gl-static-api-nginx


